name: deploy-docs
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs build
      - name: Deploy to cheddar
        uses: appleboy/scp-action@v0.1.7
        with:
          host: cheddar.ict.kth.se
          username: doc-generator
          key: ${{ secrets.CHEDDAR_WWW_KEY }}
          strip_components: 1
          source: "site/*"
          target: /var/www/cheddar.ict.kth.se/docs

