name: deploy-docs
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Cache MkDocs build cache
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Cache the Python virtual environment
      - name: Cache Python venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      # Create and activate the venv if it doesn't exist
      - name: Set up Python virtual environment
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
          fi
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Use the venv to build the docs
      - name: Build documentation
        run: |
          source .venv/bin/activate
          sudo apt install -y graphviz
          mkdocs build

      - name: Deploy to cheddar
        uses: appleboy/scp-action@v0.1.7
        with:
          host: cheddar.ict.kth.se
          username: doc-generator
          key: ${{ secrets.CHEDDAR_WWW_KEY }}
          strip_components: 1
          source: "site/*"
          target: /var/www/cheddar.ict.kth.se/docs
